# Generated by Django 4.2.29 on 2026-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='S,M,L,XL,XXL', help_text='Comma separated sizes', max_length=100),
        ),
    ]
