# Generated by Django 4.2.23 on 2026-05-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select specific products for this offer. Leave empty to apply to all products.', related_name='coupons', to='store.product'),
        ),
    ]
