# Generated by Django 4.2.23 on 2026-06-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_ize_order_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ize',
            new_name='size',
        ),
    ]
